name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch

  workflow_dispatch:
jobs:
  publish:
    name: build, pack & push
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, 'smoke_test')
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.202

      - name: pack 
        run: dotnet pack ./src/aads.csproj -o .nupkgs/

      - name: push
        run: dotnet nuget push .nupkgs/*.nupkg \
             --skip-duplicate \
             --api-key ${{secrets.NUGET_API_KEY}} \
             --source https://api.nuget.org/v3/index.json
